# Generated by Django 2.0.1 on 2018-01-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtitle', models.CharField(max_length=50)),
                ('gpic', models.ImageField(upload_to='f_goods')),
                ('gprice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('isDelete', models.BooleanField(default=False)),
                ('gunit', models.CharField(default='', max_length=20)),
                ('gclick', models.IntegerField()),
                ('gintro', models.CharField(max_length=200)),
                ('gkucun', models.IntegerField(default=0)),
            ],
        ),
    ]
