# Generated by Django 2.0.1 on 2018-01-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usex',
            field=models.CharField(default='0', max_length=2),
        ),
    ]
